# Generated by Django 5.0.6 on 2026-09-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer_accounts', '0002_seed_permissions'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('residential', 'سكني'), ('commercial', 'تجاري'), ('medical', 'طبي')], max_length=20)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=20)),
                ('main_image', models.ImageField(upload_to='project_images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='developer_accounts.developeraccount')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='locations.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['account', 'status'], name='projects_pr_account_57568c_idx'),
        ),
    ]
