# Generated by Django 5.0.6 on 2026-09-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='project',
        ),
    ]
