# Generated by Django 5.0.6 on 2026-10-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('properties', '0003_remove_property_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional link to developer project/compound.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='projects.project'),
        ),
    ]
