# Generated by Django 5.0.6 on 2026-10-02 01:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('properties', '0004_property_project'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='property_location_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
