# Generated by Django 5.0.6 on 2026-10-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('properties', '0005_property_property_location_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional link to developer project. Catalogs remain loosely coupled by design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='projects.project'),
        ),
    ]
