# Generated by Django 5.0.6 on 2026-09-04 21:20

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, validators=[apps.common.validators.validate_egyptian_phone])),
                ('message', models.TextField(blank=True, default='')),
                ('inquiry_type', models.CharField(choices=[('message', 'رسالة'), ('viewing', 'طلب معاينة'), ('call', 'طلب اتصال'), ('whatsapp', 'واتساب'), ('consultation_lead', 'استشارة عقارية ذكية')], default='message', max_length=25)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('contacted', 'تم التواصل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('whatsapp', 'واتساب'), ('phone', 'اتصال هاتفي'), ('email', 'بريد إلكتروني')], default='whatsapp', max_length=20)),
                ('preferred_time', models.DateTimeField(blank=True, null=True)),
                ('agent_notified', models.BooleanField(default=False)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'created_at'], name='inquiries_i_propert_bd3c44_idx'), models.Index(fields=['user', 'created_at'], name='inquiries_i_user_id_f71279_idx'), models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx')],
            },
        ),
    ]
