# Generated by Django 5.0.6 on 2026-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='rating',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('average', 'متوسط'), ('bad', 'سيء')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='requirement_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('ai_suggestion', 'اقتراح ذكاء اصطناعي'), ('favorite', 'المفضلة'), ('contact', 'تواصل مباشر'), ('manual', 'يدوي')], default='contact', max_length=25),
        ),
    ]
