# Generated by Django 5.0.6 on 2026-10-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_rating_inquiry_requirement_summary_and_more'),
        ('projects', '0001_initial'),
        ('properties', '0003_remove_property_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='properties.property'),
        ),
    ]
