# Generated by Django 5.0.6 on 2026-10-01 23:47

import apps.developer_accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_accounts', '0002_seed_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.developer_accounts.models.generate_token_key, max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='developer_accounts.developeruser')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
