# Generated by Django 5.0.6 on 2026-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('google', 'Google Ads'), ('tiktok', 'TikTok Ads'), ('direct', 'Direct/Organic')], default='direct', max_length=50)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=150)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
