# Generated by Django 5.0.6 on 2026-09-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinglead',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_leads', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='marketinglead',
            index=models.Index(fields=['source', 'processed'], name='marketing_m_source_67fb75_idx'),
        ),
        migrations.AddIndex(
            model_name='marketinglead',
            index=models.Index(fields=['phone'], name='marketing_m_phone_3551ac_idx'),
        ),
    ]
