# Generated by Django 5.0 on 2026-09-07
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=50, unique=True)),
                ("text", models.CharField(max_length=255)),
                ("question_type", models.CharField(default="single_choice", max_length=30)),
                ("options", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField(unique=True)),
                ("required", models.BooleanField(default=True)),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="SurveySession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("in_progress", "In progress"), ("completed", "Completed")], default="in_progress", max_length=20)),
                ("current_question_order", models.PositiveIntegerField(default=1)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="survey_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField()),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="answers", to="ai.surveyquestion")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="ai.surveysession")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("session", "question"), name="unique_survey_answer")]},
        ),
        migrations.CreateModel(
            name="SurveyResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("top_properties", models.JSONField(default=list)),
                ("session", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="result", to="ai.surveysession")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
