# Generated by Django 5.0.6 on 2026-10-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Only show this question if the user answered a specific previous question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='ai.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='depends_on_value',
            field=models.CharField(blank=True, help_text='The exact answer choice from the parent question that triggers this question.', max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
