# Generated by Django 5.0.6 on 2026-10-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_surveyquestion_depends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Leave empty = always shown. Set a parent = only shown if buyer picked a specific answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='ai.surveyquestion', verbose_name='Parent Question'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='depends_on_value',
            field=models.CharField(blank=True, help_text='The exact answer from the parent question that triggers this question.', max_length=255, verbose_name='Trigger Answer'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='key',
            field=models.SlugField(help_text='⚠️ Used by the AI engine internally. Do NOT change existing keys.', unique=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of choices as JSON. Example: ["cash", "installment", "mortgage"]. Leave empty for Free Text.'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='order',
            field=models.PositiveIntegerField(help_text='Controls the sequence. Lower number = asked first.', unique=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice (اختيار واحد)'), ('multi_choice', 'Multi Choice (اختيار متعدد)'), ('free_text', 'Free Text (كتابة حرة)'), ('currency', 'Currency / Number (مبلغ مالي)')], default='single_choice', help_text='Single Choice = one answer, Multi Choice = multiple answers, Free Text = buyer types freely.', max_length=30),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='text',
            field=models.CharField(help_text='The question text shown to the buyer (Arabic or English).', max_length=255),
        ),
    ]
